language: swift
osx_image: xcode11.3
podfile: Podfile
sudo: required

install:
    - pod install
    - gem install jazzy

script:
    - xcodebuild -workspace x5gon-mobile.xcworkspace -scheme x5gon-mobile  OBJROOT=$(PWD)/build SYMROOT=$(PWD)/build -sdk iphonesimulator 
    - source ./build-docs.sh
