language: swift
osx_image: xcode11.3
podfile: Podfile

install:
    - pod install
script:
    - xcodebuild -workspace x5gon-mobile.xcworkspace -scheme x5gon-mobile  OBJROOT=$(PWD)/build SYMROOT=$(PWD)/build Release -sdk iphonesimulator 
