language: swift
osx_image: xcode11.3
podfile: Podfile
sudo: required

git:
    submodules: false

install:
    - pod install
    - sudo gem install jazzy

script:
    - source ./scripts/build.sh -old-test
    - source ./scripts/build-docs.sh
