#!/bin/bash

echo "attempting to format code with swiftformat..."

git diff --diff-filter=d --staged --name-only | grep -e '\.swift$' | while read line; do
  swiftformat --swiftversion 5 "${line}";
  git add "$line";
done
